import pygame

print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')
print('HELLO')